ui_print "                                             "
ui_print "                                             "
ui_print "             ////////////////////            "
ui_print "          ////                  ////         "
ui_print "       ///                         ///       "
ui_print "     ///               ////////      ///     "
ui_print "    ///                ///////         //    "
ui_print "   //                  //.              //   "
ui_print "   //                  //.              //   "
ui_print "   //                  //.              //   "
ui_print "   //            ////////.              //   "
ui_print "    //         ////  ////.              //   "
ui_print "    ///        ////  ////.             //    "
ui_print "      ///       ////////             ///     "
ui_print "        ///                        ///       "
ui_print "          ////                  ////         "
ui_print "             ///////////////////             "
ui_print "                                             "
ui_print "              AMBIENT MUSIC MOD              "
ui_print "     by Kieron Quinn / Quinny899 @ XDA       "
SDK=$(getprop 'ro.build.version.sdk')
MINSDK=31
if [ "$SDK" -lt "$MINSDK" ]
then
	ui_print ""
	ui_print ""
	ui_print "Incompatible Android Version"
	ui_print "On Demand Requires Android 12 or above"
	ui_print ""
	ui_print ""
	abort "Installation aborted."
fi
ui_print ""
ui_print ""
ui_print "- Installing On Demand Overlay..."
ui_print ""
ui_print ""
ui_print "! Remember to reboot after installing"
ui_print ""
ui_print ""
ui_print "! Follow the steps linked in the FAQ to"
ui_print "! complete setup of the Google App."
ui_print ""
ui_print ""